name: terra_scope_apk
description: "Terrascope Pro - Advanced Weather & Safety Flutter App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  shared_preferences: ^2.2.3
  provider: ^6.1.2

  # Google Maps
  google_maps_flutter: ^2.5.0

  # UI & Icons
  cupertino_icons: ^1.0.8
  weather_icons: ^3.0.0
  fl_chart: ^0.68.0

  # Networking
  http: ^1.2.1

  # Location Services
  geolocator: ^14.0.2
  geocoding: ^2.1.1

  # Maps
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.6

  # Firebase
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  firebase_auth: ^6.1.2

  # Notifications
  flutter_local_notifications: ^17.2.2

  # ENV
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - lib/assets/data/crops_india.json
    - lib/assets/logo.png
    - lib/assets/images/cloudy.jpeg
    - lib/assets/images/mist.jpg
    - lib/assets/images/strom.jpg
    - lib/assets/images/sunny.jpeg
    - lib/assets/images/rainy.jpeg
    - lib/assets/images/default.jpg
